version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    ports:
      - "8000:8000"
    environment:
      TZ: "Asia/Seoul"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app --timeout 120
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - '80'
      - '443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask_app
    

